---
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Validate nginx conf
  ansible.builtin.command: nginx -t
  changed_when: false

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
