---
- name: Install Nginx reverse proxy
  hosts: nodes_web
  roles:
    - role: nginx
      target: rproxy
      external_lb_endpoint: "{{ external_lb }}"
      internal_lb_endpoint: "{{ internal_lb }}"
  tags: nginx-rproxy

- name: Install Nginx web server
  hosts: nodes_app
  roles:
    - role: nginx
      target: lemp
      external_lb_endpoint: "{{ external_lb }}"
  tags: nginx-webserver
