---
# NOTE: All role variables, which are not mentioned in this playbook,
# are defined in Terraform `run_ansible` resource

- name: Install Nginx reverse proxy
  hosts: nodes_web
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: "{{ aws_region }}"
  roles:
    - role: nginx
      target: rproxy
  tags: rproxy

- name: Install Nginx web server
  hosts: nodes_app
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: "{{ aws_region }}"
  roles:
    - role: nginx
      target: lemp
  tags: webserver

- name: Install Wordpress
  hosts: nodes_app
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: "{{ aws_region }}"
  roles:
    - role: wordpress
      wp_host: "{{ external_lb_endpoint }}"
  tags: wordpress
